#!/bin/bash
#
# Simple tasks for managing my .vim files

FILES_TO_LINK="vimrc gvimrc"
LOCALS=".vimrc.local.before .vimrc.local"

pushd $HOME/.vim

git submodule update --init --recursive

for file in $LOCALS; do
  dot_file=$HOME/$file
  touch $dot_file
done

for file in $FILES_TO_LINK; do
  dot_file=$HOME/.$file
  if [ ! -e $dot_file ]; then
    ln -s $HOME/.vim/$file $dot_file
  fi
done

if [ "$(uname)" == "Darwin" ]; then
  VIM_UPDATE_PATH=/usr/local/bin/vim-update
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
  VIM_UPDATE_PATH=$HOME/bin/vim-update
fi

if [ ! -e $VIM_UPDATE_PATH ]; then
  ln -s $HOME/.vim/update $VIM_UPDATE_PATH
fi

if which go > /dev/null; then
  echo "Installing go dependencies..."
  gopackages="\
    github.com/golang/lint/golint \
    github.com/jstemmer/gotags \
    github.com/kisielk/errcheck \
    github.com/nsf/gocode \
    golang.org/x/tools/cmd/godoc \
    golang.org/x/tools/cmd/goimports \
    golang.org/x/tools/cmd/gorename \
    golang.org/x/tools/cmd/oracle \
    golang.org/x/tools/cmd/vet \
    code.google.com/p/rog-go/exp/cmd/godef \
    "

  for p in $gopackages; do
    echo -n "${p}... "
    go get -u $p
    echo done
  done
fi

$HOME/.vim/bundle/neobundle.vim/bin/neoinstall

popd
