#!/bin/bash
#
# Simple tasks for managing my .vim files

git pull origin master
~/.vim/install

FILES_TO_LINK="vimrc gvimrc"
LOCALS=".vimrc.local.before .vimrc.local"

if [ -e ~/.vim/bundle/neobundle.vim ]; then
  echo "NeoBundle is present, updating..."
  pushd ~/.vim/bundle/neobundle.vim
  git pull origin master
  popd
  echo "Done updating NeoBundle"
else
  echo "Installing NeoBundle"
  mkdir -p ~/.vim/bundle
  git clone git://github.com/Shougo/neobundle.vim ~/.vim/bundle/neobundle.vim
  echo "Done installing NeoBundle"
fi
echo

echo "Creating local config files... "
for file in $LOCALS; do
  dot_file=~/$file
  echo "Touching $dot_file"
  touch $dot_file
done
echo "Done creating locals"
echo

echo "Symlinking... "
for file in $FILES_TO_LINK; do
  dot_file=~/$file
  if [ -e $dot_file ]; then
    echo "$dot_file already exists, skipping link."
  else
    ln -s ~/.vim/$file $dot_file
    echo "Created link for $file in your home folder."
  fi
done
echo "Done symlinking"
